name = "mach-blog"
compatibility_date = "2026-04-03"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "mach-db"
database_id = "3c76ce4a-1713-47b5-90c4-b816a45628b5"
preview_database_id = "3c76ce4a-1713-47b5-90c4-b816a45628b5"
migrations_dir = "migrations"
