name = "mach-blog"
compatibility_date = "2026-04-13"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "mach-db"
database_id = "3c76ce4a-1713-47b5-90c4-b816a45628b5"
preview_database_id = "3c76ce4a-1713-47b5-90c4-b816a45628b5"
migrations_dir = "migrations"

[vars]
VITE_TURNSTILE_SITE_KEY = "0x4AAAAAAC82fyxCiqHqWcO6"
TURNSTILE_SECRET_KEY = "0x4AAAAAAC82f4wx5i2aDIUqJ5ySkJYylic"
IMAGEKIT_PRIVATE_KEY = "private_CDF+6uVlu5z0b5uvODQUsjedVzQ="
IMAGEKIT_PUBLIC_KEY = "public_DHeodPgDB719y3hIaGJ0vJAy67I="
IMAGEKIT_URL_ENDPOINT = "https://ik.imagekit.io/5l25qpaqj"
CONTACT_FROM_EMAIL = "contact@wavionix.com"
CONTACT_FROM_NAME = "Wavionix"
CONTACT_TO_EMAIL = "Abby.logan@wavionix.com"
CONTACT_TO_NAME = "Abby Logan"
